### ISSUE TITLE
nuiWidget matrix clean up

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#14]
just to help out some cleaning up, in
~nuiwidget

for (int i=GetMatrixNodeCount();--i>=0;)
DelMatrixNode(i);

Otherwise the array is cleared without deleting the matrix nodes

**Comment by meeloo** [comment]
closed by 1416b1791756900149d23afc5f56bbf584bee0f5
Widget matrix were not properly destroyed, thanks to Jaydee2190 for finding this one.
