### ISSUE TITLE
Possible nglMouseInfo addition on iPhone

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#16]
Would it be possible(or desirable!) to have a xStart and yStart property that is set to x,y when UITouchPhaseBegan starts up as well as a nglTime of the Began phase? 

That way on Unclicked we can easily see whether it's a swipe or not. (amount of movement relative to the start of the touch and the timeinterval)

Just a thought, i'm relatively new to iphone, but I think this should be all that's required...

**Comment by meeloo** [comment]
Isn't that something that you can track in you application code? I usually do this in my widget's mouse event handling code. What benefits would you see to adding that information at the source compared to tracking it by hand?

**Comment by Jaydee2190** [comment]
Multi-touch mainly.  It'd just save from having to keep state in the widgets themselves.

**Comment by meeloo** [comment]
added a timestamp and a pointer to the counterpart event in nglMouseInfo to ease event tracking.
closed by d7d65ca0ba95e6ecc96cf33435aef121574c036e

**Comment by meeloo** [comment]
ok, as you see I think I have added what you need to ease your task :-).
Let me know if that works for you.
