### ISSUE TITLE
Small safety tweak to ~nuiSimpleContainer

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#18]
nuiSimpleContainer::~nuiSimpleContainer()
{
  CheckValid();
  // Delete all children:
  IteratorPtr pIt;
  for (pIt = GetFirstChild(false); pIt && pIt->IsValid(); GetNextChild(pIt))
  {
    nuiWidgetPtr pItem = pIt->GetWidget();
    if (pItem)
    {  
        pItem->SetParent(NULL); // If the refcount isn't 1 there's a danger of a dangling pointer to parent
        pItem->Release();

```
}
```

  }
  delete pIt;
}

**Comment by Jaydee2190** [comment]
Make that..

nuiSimpleContainer::~nuiSimpleContainer()
{
  CheckValid();
  // Delete all children:
  IteratorPtr pIt;
  for (pIt = GetFirstChild(false); pIt && pIt->IsValid(); GetNextChild(pIt))
  {
    nuiWidgetPtr pItem = pIt->GetWidget();
    if (pItem)
    {  
        if (!pItem->IsTrashed(false))
            pItem->SetParent(NULL);
        pItem->Release();

```
}
```

  }
  delete pIt;
}

**Comment by meeloo** [comment]
closed by 9cbc8fba7b197f8a7dc418f8fa85f2b2469596d1
One more down, thanks to Jaydee2190

**Comment by Jaydee2190** [comment]
Thank you Sébastien!
