### ISSUE TITLE
nuiImage release texture if in use

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#19]
I don't know if its advised to change a texture on a nuiImage, but to stop leaks...

void nuiImage::SetTexture(nuiTexture\* pTex)
{  
if (mpTexture)
mpTexture->Release();

  mpTexture = pTex;
  mUseAlpha = true;
  //SetFixedAspectRatio(true);
  mBlendFunc = nuiBlendTransp;
  SetProperty(_T("Source"), _T("Memory Buffer"));
  ResetTextureRect();
  Invalidate();
}

**Comment by meeloo** [comment]
closed by 0ee6ace9d724df627ec3520bd4d0413aadfd4205
nuiImage::SetTexture &amp; SetTexturePath wouldn&#39;t release the current texture
