### ISSUE TITLE
nuiSpriteAnimation logic reversed

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#20]
void nuiSpriteAnimation::SetDuration(float seconds)
{
  mFPS = seconds / (float)GetFrameCount();
}

should be(I think, unless my brain is acting up!)

void nuiSpriteAnimation::SetDuration(float seconds)
{
  mFPS = (float)GetFrameCount() / seconds;
}

**Comment by meeloo** [comment]
closed by 0f5d3a86eace042104b2dc04b5e3176e919e39f0
nuiSpriteAnimation::SetDuration broken
