### ISSUE TITLE
Can't build with msvc2010

### ISSUE THREAD

**Issue by vroad** [libnui/nui3#22]
I opened nui3_2010.sln, but vcxproj couldn't be loaded because it does not exist.

**Comment by meeloo** [comment]
this solution file was committed by error as we use the VS 2008 solution when we verify that everything is alright on msvc2010. We have to go through the conversion process each time which is a pain but this prevents us to maintain projects for each and every version of msvc (we already have many platforms to support and duplicating visual studio project for every change is such a chore...). How ever I'd gladly accept updated projects files if someone can update them every now and then :-).
Anyway, thanks for repporting! I'll remove the file from the repository.
