### ISSUE TITLE
Accelerometer event triggers an assert

### ISSUE THREAD

**Issue by mathieugarcia** [libnui/nui3#4]
When the UIApplication receive an Accelerometer event (UIMotionEvent), the event handling in nglUIWindow asserts as it expects a touch/gesture event. Test device: iPod Touch 4G / latest NUI / Fw revision 4.1.

Backtrace:

<pre>
#0  0x30e66ac8 in __kill ()
#1  0x30e66abe in kill ()
#2  0x30e66ab0 in raise ()
#3  0x30e7b040 in abort ()
#4  0x30e69142 in __assert_rtn ()
#5  0x0087c490 in -[nglUIWindow handleEvent:] (self=0x1d5f9a0, _cmd=0x32783c6e, pEvent=0x1d494c0) at nui3/src/Window/UIKit/nglWindow_UIKit.mm:447
#6  0x0087d3f0 in -[nglUIWindow sendEvent:] (self=0x1d5f9a0, _cmd=0x32783c49, pEvent=0x1d494c0) at nui3/src/Window/UIKit/nglWindow_UIKit.mm:365
#7  0x316099fe in -[UIApplication sendEvent:] ()
#8  0x00875c0c in -[nglUIApplication sendEvent:] (self=0x1d48e90, _cmd=0x32783c49, pEvent=0x1d494c0) at nui3/src/Application/UIKit/nglApplication_UIKit.mm:40
#9  0x316b9450 in -[UIApplication _sendMotionBegan:] ()
#10 0x3174f4e6 in -[UIMotionEvent accelerometer:didAccelerateWithTimeStamp:x:y:z:eventType:] ()
#11 0x354ed6c0 in _SBXXDeliverAccelerometerEvent ()
#12 0x354ed7d0 in _XDeliverAccelerometerEvent ()
#13 0x354b7062 in migHelperRecievePortCallout ()
#14 0x349bace2 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#15 0x349baca6 in __CFRunLoopDoSource1 ()
#16 0x349ad56c in __CFRunLoopRun ()
#17 0x349ad276 in CFRunLoopRunSpecific ()
#18 0x349ad17e in CFRunLoopRunInMode ()
#19 0x311dc5f2 in GSEventRunModal ()
#20 0x311dc69e in GSEventRun ()
#21 0x315b0122 in -[UIApplication _run] ()
#22 0x315ae12e in UIApplicationMain ()
#23 0x00874990 in nglApplication::Main (this=0x1d3dc00, argc=1, argv=0x2ffff56c) at nui3/src/Application/UIKit/nglApplication_UIKit.mm:215
</pre>

**Comment by meeloo** [comment]
fixed in head
