### ISSUE TITLE
Crash exiting iApp via Home button

### ISSUE THREAD

**Issue by haiku31** [libnui/nui3#5]
Bug exiting iApp using the Home button (OS 4.1):
#0 0x003eb92c in nuiStateDecoration::~nuiStateDecoration at nuiStateDecoration.cpp:72
#1 0x003eb898 in virtual thunk to nuiStateDecoration::~nuiStateDecoration() at nuiStateDecoration.cpp:627
#2 0x00496658 in nuiRefCount::Release at nuiRefCount.h:46
#3 0x003d2d5c in nuiDecoration::ExitDecorationEngine at nuiDecoration.cpp:405
#4 0x002ffbd0 in nuiUninit at nuiInit.cpp:168
#5 0x0012741c in MyApp::OnExit at nuiVariant.h:343

pDecoration->Release();

Does not happen everytime

**Comment by meeloo** [comment]
should be fixed now.
